// Constraint: the status codes declared by `#[utoipa::path]` annotations must match what the
// handlers actually return.

use axum::body::Bytes;
use axum::http::header;
use axum::response::IntoResponse;
use std::sync::LazyLock;
use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::dto::{
    CreateScriptReq, CreateScriptVersionReq, CreateSpaceReq, ErrorBodyDto, HealthDto, ScriptDto,
    SpaceDto, UpdateScriptReq, VersionDto, VersionMetaDto,
};
use crate::routes::{scripts, spaces};

pub struct SpaceKeySecurityAddon;

impl Modify for SpaceKeySecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "space_key",
            SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("X-Space-Key"))),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "oncewise-ai-sync",
        version = "0.1.0",
        description = "OnceWise Flow script sync backend: key-addressed spaces with scripts and immutable versions. No account system — ids are generated by clients; the server only stores and distributes structured script data, it never generates or executes flows."
    ),
    components(schemas(
        ErrorBodyDto, HealthDto, ScriptDto, SpaceDto, VersionDto, VersionMetaDto,
        CreateSpaceReq, CreateScriptReq, CreateScriptVersionReq, UpdateScriptReq,
    )),
    modifiers(&SpaceKeySecurityAddon),
    paths(
        spaces::create_space,
        spaces::get_space,
        spaces::delete_space,
        spaces::get_health,
        scripts::create_script,
        scripts::list_scripts,
        scripts::update_script,
        scripts::create_script_version,
        scripts::list_script_versions,
        scripts::get_script_version,
        get_openapi,
    )
)]
pub struct ApiDoc;

/// The document is fixed at compile time: serialize once and cache the bytes instead of
/// re-assembling + re-serializing per request.
static OPENAPI_BYTES: LazyLock<Bytes> = LazyLock::new(|| {
    Bytes::from(serde_json::to_vec(&ApiDoc::openapi()).expect("OpenAPI serialization failed"))
});

/// `GET /api/openapi.json`: export the OpenAPI 3 document (for consistency checks and as the
/// extension-side type reference).
#[utoipa::path(
    get,
    path = "/api/openapi.json",
    tag = "ops",
    responses((status = 200, description = "OpenAPI 3 JSON document", content_type = "application/json"))
)]
pub async fn get_openapi() -> impl IntoResponse {
    (
        [(header::CONTENT_TYPE, "application/json")],
        OPENAPI_BYTES.clone(),
    )
}
